### ISSUE TITLE
Why is the starting point of the detected CNV always an integer+1

### ISSUE THREAD

**Issue by linlin-coder** [PacificBiosciences/HiFiCNV#12]
Hello HiFICNV developer, when I used the HIFICNV tool to detect CNVs, I found that the starting point of the CNV was always integer001, the format of the ending point was always integer000, and the length of the CNV was always integer000. This is not consistent with my analysis results and experience using next-generation WGS sequencing data.

My analysis software and solution are as follows:

pbmm2 -> hificnv(v0.1.5)

Run the command as follows:
```shell
hificnv-v0.1.5-x86_64-unknown-linux-gnu/hificnv \
 --bam sample1.sort.bam \
 --ref Homo_sapiens_assembly38.onlychr.fasta \
 --exclude hificnv-v0.1.5-x86_64-unknown-linux-gnu/data/excluded_regions/cnv.excluded_regions.common_50.hg38.bed.gz \
 --threads 20 \
 --output-prefix CallCNV_hificnv-v0.1.6
```
![image](https://github.com/PacificBiosciences/HiFiCNV/assets/77706356/e7ecb83c-03f6-4011-ab26-9b8ade79393d)

**Comment by holtjma** [comment]
Hello,

This is the expected behavior.  HiFiCNV is a depth-based CNV caller, specifically intended to identify large variants where precise breakpoints are difficult to capture with sequencing data due to sequence homology at the breakpoints.  In contrast, tools like `pbsv` are break-end callers and will typically have basepair level resolution for called events.  For HiFiCNV, the underlying algorithm using a bin size of 2 kbp by default (see https://github.com/PacificBiosciences/HiFiCNV/blob/main/docs/methods.md).  This is why all of the start/end positions are at 2 kbp boundaries.

Does that answer the question?

**Comment by linlin-coder** [comment]
I understand, that is, because of the sequence homology at the breakpoint, the chromosomes are evenly divided and the read depth of each window is calculated to see which segments have continuous read depth changes and are defined as CNV regions. I am not sure if my understanding is correct

**Comment by linlin-coder** [comment]
I understand. Thank you for your answer

**Comment by MKaandemir** [comment]
Shouldn't the starting point be at position -1 since there should be a padding base?
