### ISSUE TITLE
configuration files (hg19 support)

### ISSUE THREAD

**Issue by huangrongbioinfomation** [PacificBiosciences/HiFiCNV#9]
If I use the hg19 version reference genome,
How are these configuration files obtained?
cnv.excluded_regions.common_50.hg38.bed.gz
female_expected_cn.hg38.bed
male_expected_cn.hg38.bed

**Comment by huangrongbioinfomation** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到邮件

**Comment by huangrongbioinfomation** [comment]
hg19 reference genome has no centromeres.txt.gz file,
<img width="526" alt="image" src="https://user-images.githubusercontent.com/54733697/233272524-f57308ba-93fe-4072-8a17-0518ee6290cb.png">

Can you provide the configuration file for the hg19?
cnv.excluded_regions.common_50.hg38.bed.gz
female_expected_cn.hg38.bed
male_expected_cn.hg38.bed

**Comment by holtjma** [comment]
It looks like that data file doesn't exist for hg19.  However, I think you might be okay without it.  I modified the to hg19 (also had to change the filename on the next line) and produced a file with centromeres included:

```
(base) [mholt@vm-login7-01 test_folder]$ gunzip -c cnv.excluded_regions.hg19.bed.gz | grep centromere
chr1	121535434	124535434	centromere
chr10	39254935	42254935	centromere
chr11	51644205	54644205	centromere
chr12	34856694	37856694	centromere
chr13	16000000	19000000	centromere
chr14	16000000	19000000	centromere
chr15	17000000	20000000	centromere
chr16	35335801	38335801	centromere
chr17	22263006	25263006	centromere
chr18	15460898	18460898	centromere
chr19	24681782	27681782	centromere
chr2	92326171	95326171	centromere
chr20	26369569	29369569	centromere
chr21	11288129	14288129	centromere
chr22	13000000	16000000	centromere
chr3	90504854	93504854	centromere
chr4	49660117	52660117	centromere
chr5	46405641	49405641	centromere
chr6	58830166	61830166	centromere
chr7	58054331	61054331	centromere
chr8	43838887	46838887	centromere
chr9	47367679	50367679	centromere
chrX	58632012	61632012	centromere
chrY	10104553	13104553	centromere
```

This should work with HiFiCNV, but I have not tested it.  This link should have the information you need for the hg19 PAR regions: https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.13/#/def_region-PAR1

I'll make a note of the request for more formalized hg19 support.

**Comment by huangrongbioinfomation** [comment]
The web only provides the  4 columns of information, how to get the last column of information？
How to get chrX_uniq information?
<img width="739" alt="image" src="https://user-images.githubusercontent.com/54733697/233518411-aa067150-68b2-4413-be8e-238a8c476aa3.png">

**Comment by huangrongbioinfomation** [comment]
Are the contents of male_expected_cn.hg38.bed and female_expected_cn.hg38.bed the same?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/54733697/233518560-f663a810-a55b-4766-8bb3-67f1ef966173.png">

**Comment by huangrongbioinfomation** [comment]
How to get the last column for male and female
![屏幕快照 2023-04-21 下午4 53 47](https://user-images.githubusercontent.com/54733697/233592180-2de621df-df73-44d4-9df5-664454a6a26c.png)

**Comment by holtjma** [comment]
@huangrongbioinfomation That final column is the expected copy number count for the region, which is derived from both the expectations for pseudo-autosomal regions (PAR) and how our reference file is masked.  In the hg38 reference we use, there are two PAR regions that we expect to appear on both male and female chromosomes.  Because they appear on both, we expect each to have two copies in a normal WGS sample.  This is why in our released files `chrX_PAR_1` and `chrX_PAR_2` are both set to "2" for both male and female.  Additionally, even though these appear on chrY as well as `chrY_PAR_1` and `chrY_PAR_2`, they are masked out so the copy number is always "0".  The last regions, `chrX_uniq_1` and `chrY_uniq_1`, are unique to X and Y respectively.  For females we expect 2 and 0 copies, whereas for males we expect 1 and 1.
